<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;

/**
 * Resume Parsing Service
 * 
 * Extracts structured information from raw CV text using pure regex/rule-based parsing.
 * NO Gemini API calls - completely free and offline.
 * 
 * Extracts: name, email, phone, summary, experience, education, skills, certifications
 */
class ResumeParsingService
{
    /**
     * Parse raw CV text into a structured resume array.
     *
     * @param string $cvText Raw text extracted from CV file
     * @return array Structured resume data
     */
    public function parse(string $cvText): array
    {
        $lines = explode("\n", $cvText);
        $lines = array_map('trim', $lines);
        $lines = array_filter($lines, fn($l) => $l !== '');
        $lines = array_values($lines); // Re-index

        return [
            'name'           => $this->extractName($lines),
            'email'          => $this->extractEmail($cvText),
            'phone'          => $this->extractPhone($cvText),
            'address'        => $this->extractAddress($lines),
            'summary'        => $this->extractSummary($lines),
            'experience'     => $this->extractExperience($lines),
            'education'      => $this->extractEducation($lines),
            'skills'         => $this->extractSkills($lines),
            'certifications' => $this->extractCertifications($lines),
            'languages'      => $this->extractLanguages($lines),
        ];
    }

    /**
     * Generate formatted text version of the resume for download.
     */
    public function toText(array $resume): string
    {
        $lines = [];
        $lines[] = str_repeat('=', 60);
        $lines[] = str_pad('RESUME', 60, ' ', STR_PAD_BOTH);
        $lines[] = str_repeat('=', 60);
        $lines[] = '';

        // Name & Contact
        $lines[] = strtoupper($resume['name'] ?? 'Unknown');
        $lines[] = str_repeat('-', 40);
        if (!empty($resume['email'])) $lines[] = "Email: {$resume['email']}";
        if (!empty($resume['phone'])) $lines[] = "Phone: {$resume['phone']}";
        if (!empty($resume['address'])) $lines[] = "Address: {$resume['address']}";
        $lines[] = '';

        // Summary
        if (!empty($resume['summary'])) {
            $lines[] = 'PROFESSIONAL SUMMARY';
            $lines[] = str_repeat('-', 40);
            $lines[] = $resume['summary'];
            $lines[] = '';
        }

        // Experience
        if (!empty($resume['experience'])) {
            $lines[] = 'WORK EXPERIENCE';
            $lines[] = str_repeat('-', 40);
            foreach ($resume['experience'] as $exp) {
                if (!empty($exp['title'])) $lines[] = "• {$exp['title']}";
                if (!empty($exp['company'])) $lines[] = "  {$exp['company']}";
                if (!empty($exp['period'])) $lines[] = "  {$exp['period']}";
                if (!empty($exp['description'])) {
                    foreach ((array)$exp['description'] as $desc) {
                        $lines[] = "  - {$desc}";
                    }
                }
                $lines[] = '';
            }
        }

        // Education
        if (!empty($resume['education'])) {
            $lines[] = 'EDUCATION';
            $lines[] = str_repeat('-', 40);
            foreach ($resume['education'] as $edu) {
                $parts = [];
                if (!empty($edu['degree'])) $parts[] = $edu['degree'];
                if (!empty($edu['institution'])) $parts[] = $edu['institution'];
                if (!empty($edu['year'])) $parts[] = "({$edu['year']})";
                if (!empty($parts)) $lines[] = "• " . implode(' - ', $parts);
            }
            $lines[] = '';
        }

        // Skills
        if (!empty($resume['skills'])) {
            $lines[] = 'SKILLS';
            $lines[] = str_repeat('-', 40);
            $lines[] = implode(', ', $resume['skills']);
            $lines[] = '';
        }

        // Certifications
        if (!empty($resume['certifications'])) {
            $lines[] = 'CERTIFICATIONS';
            $lines[] = str_repeat('-', 40);
            foreach ($resume['certifications'] as $cert) {
                $lines[] = "• {$cert}";
            }
            $lines[] = '';
        }

        // Languages
        if (!empty($resume['languages'])) {
            $lines[] = 'LANGUAGES';
            $lines[] = str_repeat('-', 40);
            $lines[] = implode(', ', $resume['languages']);
            $lines[] = '';
        }

        $lines[] = str_repeat('=', 60);
        $lines[] = 'Generated by CVision AI Engine';
        $lines[] = 'Date: ' . now()->format('Y-m-d H:i');
        $lines[] = str_repeat('=', 60);

        return implode("\n", $lines);
    }

    /**
     * Extract name from CV (usually first non-empty line).
     */
    private function extractName(array $lines): string
    {
        // Skip lines that look like emails, phones, or URLs
        foreach ($lines as $line) {
            if (strlen($line) > 2 && strlen($line) < 60
                && !preg_match('/@|http|www|phone|telp|email|address|alamat/i', $line)
                && !preg_match('/^\d/', $line)) {
                return $line;
            }
        }
        return $lines[0] ?? 'Unknown';
    }

    /**
     * Extract email address from CV text.
     */
    private function extractEmail(string $text): string
    {
        preg_match('/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/', $text, $matches);
        return $matches[0] ?? '';
    }

    /**
     * Extract phone number from CV text.
     */
    private function extractPhone(string $text): string
    {
        preg_match('/(\+?[\d\s\-\(\)]{7,15})/', $text, $matches);
        return $matches[0] ?? '';
    }

    /**
     * Extract address/location from CV.
     */
    private function extractAddress(array $lines): string
    {
        $keywords = ['address', 'alamat', 'domicile', 'domisili', 'location', 'lokasi', 'city', 'kota'];
        foreach ($lines as $line) {
            $lower = strtolower($line);
            foreach ($keywords as $kw) {
                if (str_contains($lower, $kw) && strlen($line) > 5 && strlen($line) < 100) {
                    // Return the value after the keyword
                    $parts = preg_split('/[:|]\s*/', $line, 2);
                    return trim(end($parts));
                }
            }
        }
        return '';
    }

    /**
     * Extract professional summary from CV.
     */
    private function extractSummary(array $lines): string
    {
        $summaryLines = [];
        $inSummary = false;
        $summaryKeywords = ['summary', 'ringkasan', 'profile', 'profil', 'about', 'tentang', 'objective', 'tujuan'];

        foreach ($lines as $line) {
            $lower = strtolower($line);
            
            // Detect summary section header
            if (!$inSummary) {
                foreach ($summaryKeywords as $kw) {
                    if (str_contains($lower, $kw) && strlen($line) < 40) {
                        $inSummary = true;
                        break;
                    }
                }
                continue;
            }

            // Stop at next section header
            if (preg_match('/^(experience|pengalaman|education|pendidikan|skills|keahlian|work|employment)/i', $lower)) {
                break;
            }

            if (strlen($line) > 20) {
                $summaryLines[] = $line;
            }
        }

        // If no summary section found, take first meaningful lines
        if (empty($summaryLines)) {
            foreach ($lines as $i => $line) {
                if ($i > 0 && $i < 6 && strlen($line) > 30
                    && !preg_match('/@|http|www|phone|telp/i', $line)) {
                    $summaryLines[] = $line;
                }
            }
        }

        return implode(' ', array_slice($summaryLines, 0, 3));
    }

    /**
     * Extract work experience from CV.
     */
    private function extractExperience(array $lines): array
    {
        $experiences = [];
        $currentExp = null;
        $inExperience = false;
        $expKeywords = ['experience', 'pengalaman', 'work history', 'employment', 'riwayat pekerjaan'];

        foreach ($lines as $i => $line) {
            $lower = strtolower($line);

            // Detect experience section
            if (!$inExperience) {
                foreach ($expKeywords as $kw) {
                    if (str_contains($lower, $kw) && strlen($line) < 40) {
                        $inExperience = true;
                        break;
                    }
                }
                continue;
            }

            // Stop at next major section
            if (preg_match('/^(education|pendidikan|skills|keahlian|education|sertifikat|certification)/i', $lower)) {
                break;
            }

            // Detect date patterns (e.g., "2020 - Present", "Jan 2020 - Dec 2022")
            $datePattern = '/(\d{4})\s*[-–]\s*(\d{4}|present|now|saat\s*ini)/i';
            if (preg_match($datePattern, $line)) {
                if ($currentExp && !empty($currentExp['title'])) {
                    $experiences[] = $currentExp;
                }
                $currentExp = [
                    'title'       => $lines[$i - 1] ?? '',
                    'company'     => preg_replace($datePattern, '', $line),
                    'period'      => '',
                    'description' => [],
                ];
                preg_match($datePattern, $line, $dateMatches);
                $currentExp['period'] = $dateMatches[0] ?? '';
                $currentExp['company'] = trim(str_replace($currentExp['period'], '', $line));
                continue;
            }

            // Add description to current experience
            if ($currentExp && strlen($line) > 15) {
                $currentExp['description'][] = $line;
            }
        }

        // Save last experience
        if ($currentExp && !empty($currentExp['title'])) {
            $experiences[] = $currentExp;
        }

        return $experiences;
    }

    /**
     * Extract education from CV.
     */
    private function extractEducation(array $lines): array
    {
        $education = [];
        $inEducation = false;
        $eduKeywords = ['education', 'pendidikan', 'academic', 'akademik', 'university', 'universitas', 'college'];

        foreach ($lines as $i => $line) {
            $lower = strtolower($line);

            // Detect education section
            if (!$inEducation) {
                foreach ($eduKeywords as $kw) {
                    if (str_contains($lower, $kw) && strlen($line) < 40) {
                        $inEducation = true;
                        break;
                    }
                }
                continue;
            }

            // Stop at next major section
            if (preg_match('/^(skills|keahlian|experience|pengalaman|certification|sertifikat|project)/i', $lower)) {
                break;
            }

            // Skip section headers and short lines
            if (strlen($line) < 10) {
                continue;
            }

            // Detect degree level from line - check for specific patterns
            $degree = '';
            $institution = $line;
            $year = '';

            // Extract year if present
            $yearPattern = '/(\d{4})\s*[-–]\s*(\d{4}|present|now|saat\s*ini)/i';
            if (preg_match($yearPattern, $line, $yearMatches)) {
                $year = $yearMatches[0];
            }

            // Check for degree keywords in order of specificity
            // Use preg_match to find degree abbreviation in the line
            // Note: Check D3/D4 before S1/S2 to avoid matching wrong degree
            if (preg_match('/(d3|d4|d1|d2)/i', $line, $degMatch)) {
                $degree = strtoupper($degMatch[1]);
            } elseif (preg_match('/(s1|s2|s3)/i', $line, $degMatch)) {
                $degree = strtoupper($degMatch[1]);
            } elseif (preg_match('/(sma|smk)/i', $line, $degMatch)) {
                $degree = strtoupper($degMatch[1]);
            } elseif (preg_match('/(bachelor)/i', $line)) {
                $degree = 'Bachelor';
            } elseif (preg_match('/(master)/i', $line)) {
                $degree = 'Master';
            } elseif (preg_match('/(doctor|phd)/i', $line)) {
                $degree = 'Doctor';
            } elseif (preg_match('/(diploma)/i', $line)) {
                $degree = 'Diploma';
            }

            // If degree found, add to education list
            if ($degree) {
                $education[] = [
                    'degree'      => $degree,
                    'institution' => $institution,
                    'year'        => $year,
                    'gpa'         => '',
                ];
            }
        }

        return $education;
    }

    /**
     * Extract skills from CV.
     */
    private function extractSkills(array $lines): array
    {
        $skills = [];
        $inSkills = false;
        $skillKeywords = ['skills', 'keahlian', 'technical skills', 'kompetensi', 'kemampuan'];

        foreach ($lines as $line) {
            $lower = strtolower($line);

            // Detect skills section
            if (!$inSkills) {
                foreach ($skillKeywords as $kw) {
                    if (str_contains($lower, $kw) && strlen($line) < 40) {
                        $inSkills = true;
                        break;
                    }
                }
                continue;
            }

            // Stop at next major section
            if (preg_match('/^(education|pendidikan|experience|pengalaman|certification|sertifikat|project|language)/i', $lower)) {
                break;
            }

            // Split comma-separated skills
            $parts = preg_split('/[,|;]\s*/', $line);
            foreach ($parts as $part) {
                $part = trim($part);
                if (strlen($part) > 1 && strlen($part) < 50) {
                    $skills[] = $part;
                }
            }
        }

        return array_unique($skills);
    }

    /**
     * Extract certifications from CV.
     */
    private function extractCertifications(array $lines): array
    {
        $certs = [];
        $inCerts = false;
        $certKeywords = ['certification', 'certificate', 'sertifikat', 'sertifikasi'];

        foreach ($lines as $line) {
            $lower = strtolower($line);

            if (!$inCerts) {
                foreach ($certKeywords as $kw) {
                    if (str_contains($lower, $kw) && strlen($line) < 40) {
                        $inCerts = true;
                        break;
                    }
                }
                continue;
            }

            if (preg_match('/^(education|pendidikan|experience|pengalaman|skills|keahlian|language)/i', $lower)) {
                break;
            }

            if (strlen($line) > 5 && strlen($line) < 100) {
                $certs[] = $line;
            }
        }

        return $certs;
    }

    /**
     * Extract languages from CV.
     */
    private function extractLanguages(array $lines): array
    {
        $languages = [];
        $inLang = false;
        $langKeywords = ['language', 'bahasa', 'languages'];

        foreach ($lines as $line) {
            $lower = strtolower($line);

            if (!$inLang) {
                foreach ($langKeywords as $kw) {
                    if (str_contains($lower, $kw) && strlen($line) < 40) {
                        $inLang = true;
                        break;
                    }
                }
                continue;
            }

            if (preg_match('/^(education|pendidikan|experience|pengalaman|skills|keahlian|certification)/i', $lower)) {
                break;
            }

            if (strlen($line) > 3 && strlen($line) < 80) {
                $languages[] = $line;
            }
        }

        return $languages;
    }
}