"""
Resume Generator Service
Uses Gemini AI to structure raw CV text into a clean, organized resume format.
Also generates a PDF version for download.
"""

import sys
import json
import logging
from datetime import datetime
from typing import Any

# Fix for Windows console encoding (cp1252) - enable UTF-8 output
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

logger = logging.getLogger(__name__)


class ResumeGenerator:
    """
    Generates structured resumes from raw CV text using Gemini AI.
    Falls back to rule-based extraction if Gemini is unavailable.
    """

    def __init__(self, gemini_client=None):
        self.gemini_client = gemini_client

    def generate_structured_resume(self, cv_text: str) -> dict[str, Any]:
        """
        Generate a structured resume from raw CV text.
        Note: Resume parsing is handled by Laravel backend (ResumeParsingService).
        This method returns a minimal placeholder.

        Args:
            cv_text: Raw text extracted from PDF

        Returns:
            Structured resume dictionary
        """
        logger.info("Resume parsing delegated to Laravel backend")
        return {
            "name": "Unknown",
            "email": "",
            "phone": "",
            "summary": "Resume parsing is handled by Laravel backend.",
            "experience": [],
            "education": [],
            "skills": [],
            "raw_text": cv_text[:1000] if cv_text else "",
            "generated_at": datetime.now().isoformat()
        }

    def generate_resume_text(self, structured_resume: dict) -> str:
        """
        Convert structured resume to formatted text.

        Args:
            structured_resume: Resume dictionary

        Returns:
            Formatted text suitable for display
        """
        lines = []
        lines.append("=" * 60)
        lines.append(f"{'RESUME':^60}")
        lines.append("=" * 60)
        lines.append("")
        
        # Name & Contact
        lines.append(structured_resume.get('name', 'Unknown').upper())
        lines.append("-" * 40)
        if structured_resume.get('email'):
            lines.append(f"Email: {structured_resume['email']}")
        if structured_resume.get('phone'):
            lines.append(f"Phone: {structured_resume['phone']}")
        lines.append("")
        
        # Professional Summary
        summary = structured_resume.get('summary', '')
        if summary:
            lines.append("PROFESSIONAL SUMMARY")
            lines.append("-" * 40)
            lines.append(summary)
            lines.append("")
        
        # Experience
        experience = structured_resume.get('experience', [])
        if experience:
            lines.append("WORK EXPERIENCE")
            lines.append("-" * 40)
            for exp in experience:
                if exp.get('title'):
                    lines.append(f"* {exp['title']}")
                if exp.get('company'):
                    lines.append(f"  {exp['company']}")
                if exp.get('period'):
                    lines.append(f"  {exp['period']}")
                for desc in exp.get('description', []):
                    lines.append(f"  - {desc}")
                lines.append("")
        
        # Education
        education = structured_resume.get('education', [])
        if education:
            lines.append("EDUCATION")
            lines.append("-" * 40)
            for edu in education:
                line_parts = []
                if edu.get('degree'):
                    line_parts.append(edu['degree'])
                if edu.get('institution'):
                    line_parts.append(edu['institution'])
                if edu.get('year'):
                    line_parts.append(f"({edu['year']})")
                if line_parts:
                    lines.append(f"* {' - '.join(line_parts)}")
            lines.append("")
        
        # Skills
        skills = structured_resume.get('skills', [])
        if skills:
            lines.append("SKILLS")
            lines.append("-" * 40)
            lines.append(f"{', '.join(skills)}")
            lines.append("")
        
        lines.append("=" * 60)
        lines.append(f"Generated by CVision AI Engine")
        lines.append(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        lines.append("=" * 60)
        
        return '\n'.join(lines)